spring:
  application.name: sisepe
  datasource:
    url: jdbc:postgresql://localhost:5432/sisepe
    username: postgres
    password: ${SENHA_DB}
  jpa.hibernate.ddl-auto: validate
  flyway:
    baseline-on-migrate: true
  main:
    web-application-type: servlet

server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-stacktrace: never
